### Login as student
POST http://127.0.0.1:8000/users/login/
Content-Type: application/x-www-form-urlencoded

username=teached1&password=12345678teached1

> {% client.global.set("student_access_token", response.body.access_token); %}


### Student enrolled courses
GET http://127.0.0.1:8000/my-classroom/
Content-Type: application/json
Authorization: Bearer {{student_access_token}}

