### Login as teacher
POST http://127.0.0.1:8000/users/login/
Content-Type: application/x-www-form-urlencoded

username=teached&password=123456789teached


> {% client.global.set("teacher_access_token", response.body.access_token); %}

### Login as student
POST http://127.0.0.1:8000/users/login/
Content-Type: application/x-www-form-urlencoded

username=teached1&password=12345678teached1


> {% client.global.set("student_access_token", response.body.access_token); %}

### create course
POST http://127.0.0.1:8000/courses/
Content-Type: application/json
Authorization: Bearer {{teacher_access_token}}

{
  "title": "Python 101",
  "overview": "Python tutorial",
  "categories": ["Development", "Python", "programing"],
  "languages": ["English"],
  "requirements": [],
  "level": "beginner",
  "price": 0,
  "discount": 0
}

> {% client.global.set("course_slug", response.body.slug); %}

### course list
GET http://127.0.0.1:8000/courses/
Content-Type: application/json


### course detail
GET http://127.0.0.1:8000/courses/{{course_slug}}/
Content-Type: application/json
Authorization: Bearer {{student_access_token}}


### course enroll
POST http://127.0.0.1:8000/courses/{{course_slug}}/
Content-Type: application/json
Authorization: Bearer {{student_access_token}}

### bookmark a course
POST http://127.0.0.1:8000/courses/{{course_slug}}/bookmark/
Content-Type: application/json
Authorization: Bearer {{student_access_token}}


### bookmark
GET http://127.0.0.1:8000/courses/bookmarks/
Content-Type: application/json
Authorization: Bearer {{student_access_token}}


### course a review
POST http://127.0.0.1:8000/courses/{{course_slug}}/review/
Content-Type: application/json
Authorization: Bearer {{student_access_token}}

{"review":  "Good course", "rate": 5}


### course a review
GET http://127.0.0.1:8000/courses/{{course_slug}}/review/
Content-Type: application/json

### create course section
POST http://127.0.0.1:8000/courses/{{course_slug}}/manage/section/
Content-Type: application/json
Authorization: Bearer {{teacher_access_token}}

{
  "title": "Python basic structure",
  "objective":  "This section you will learn basic stuff about python",
  "order": 1
}

> {% client.global.set("section_slug", response.body.slug); %}


### create section lecture
POST http://127.0.0.1:8000/courses/{{course_slug}}/manage/section/{{section_slug}}/lecture/
Content-Type: application/json
Authorization: Bearer {{teacher_access_token}}

{
  "title": "Python syntax",
  "text":  "x = 1 + 1",
  "order": 1
}

> {% client.global.set("lecture_slug", response.body.slug); %}

### create section assignment
POST http://127.0.0.1:8000/courses/{{course_slug}}/manage/section/{{section_slug}}/assignment/
Content-Type: application/json
Authorization: Bearer {{teacher_access_token}}

{
  "title": "Python syntax assignment",
  "description":  "basic Python syntax assignment"
}

> {% client.global.set("assignment_slug", response.body.slug); %}


### create course announcement
POST http://127.0.0.1:8000/courses/{{course_slug}}/manage/announcement/
Content-Type: application/json
Authorization: Bearer {{teacher_access_token}}

{
  "title": "Update",
  "description":  "The course will be updated in 2021"
}

> {% client.global.set("assignment_slug", response.body.slug); %}

### update course settings
PATCH http://127.0.0.1:8000/courses/{{course_slug}}/manage/settings/
Content-Type: application/json
Authorization: Bearer {{teacher_access_token}}

{
  "is_drift": false
}
